# Setup
title:               Cindy Cheng
tagline:             Political Scientist
baseurl:             "/webpage"
url:                 https://cindyyawencheng.github.io


# About/contact
author:
  name:                Cindy Cheng
  email:               "cindy.cheng@hfp.tum.de" # email here 
  avatar:              img/profile.jpg 
  profile-pic:         img/profile.jpg
  github_username:      cindyyawencheng


# Build settings
markdown:            kramdown
permalink:           
sass:
  sass_dir:          _sass
  style:            :compressed


kramdown:
  input: GFM


collections:
  category:
    output: true

# Default settings
defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: Gabriel Utterson
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "post"
      
